### ISSUE TITLE
Not working with MongoDB 3.2.0

### ISSUE THREAD

**Issue by hybr1dz** [DanWahlin/CustomerManagerStandard#26]
The Visual Studio and .NET build is working fine, but i'm looking to get it working with the MEAN stack. I have node-v5.2.0 and MongoDB 3.2.0. It starts up fine and the page loads, but it doesn't show any customer data (i have imported the data to MongoDB and the node.js window says "Customers count: 23"). I get following errors in browser console:
```javascript
angular.js:12221SyntaxError: Unexpected token u
    at Object.parse (native)
    at vc (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.0/angular.min.js:15:313)
    at $b (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.0/angular.min.js:81:301)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.4.0/angular.min.js:82:216
    at n (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.0/angular.min.js:7:322)
    at ed (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.0/angular.min.js:82:198)
    at c (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.0/angular.min.js:83:382)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.4.0/angular.min.js:119:302
    at m.$eval (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.0/angular.min.js:134:83)
    at m.$digest (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.0/angular.min.js:131:106)(anonymous function) @ angular.js:12221
angular.js:12221TypeError: Cannot read property 'message' of undefined
    at customersController.js:124
    at angular.js:14454
    at m.$eval (angular.js:15719)
    at m.$digest (angular.js:15530)
    at m.$apply (angular.js:15824)
    at l (angular.js:10263)
    at M (angular.js:10435)
    at XMLHttpRequest.x.onload (angular.js:10376)
```
I've looked at the code a bit and there might be a problem on getCustomersSummary()-function in accessDB.js. The customersSummary that is in the callback seems to be left "undefined".

**Comment by hybr1dz** [comment]
It looks like problem is related to MongoDB version. I tried 2.6.11 and it works fine on it.

**Comment by DanWahlin** [comment]
Thanks for the information. This turned out to be related to an apparent breaking change in how Mongo handles skipping and taking records. Just updated the code base to get it working with Mongo 3.2 (latest version as of today).
